# Generated by Django 5.0.1 on 2024-01-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('publishedate', models.DateField()),
            ],
        ),
    ]
