# Generated by Django 5.0.1 on 2024-01-26 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_book_book1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book1',
            new_name='Book',
        ),
    ]
